#!/usr/bin/env bash
# Generates internal/buildinfo/buildinfo.go from the current .version + git state.
# Idempotent: only rewrites the file if its contents would change.
set -uo pipefail

cd "$(dirname "$0")/.."

VERSION_FILE=".version"
OUT="internal/buildinfo/buildinfo.go"

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "error: $VERSION_FILE missing" >&2
  exit 1
fi

VERSION=$(tr -d '\n' < "$VERSION_FILE")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || true)
COMMIT=${COMMIT//$'\n'/}
[[ -z "$COMMIT" ]] && COMMIT="unknown"
BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || true)
BRANCH=${BRANCH//$'\n'/}
[[ -z "$BRANCH" ]] && BRANCH="unknown"
DATE=$(git log -1 --format='%cd' --date=format:'%Y-%m-%d %H:%M:%S UTC' 2>/dev/null || true)
DATE=${DATE//$'\n'/}
[[ -z "$DATE" ]] && DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
GOVERSION=$(go version 2>/dev/null | awk '{print $3}' | sed 's/^go//' || true)
GOVERSION=${GOVERSION//$'\n'/}
[[ -z "$GOVERSION" ]] && GOVERSION="unknown"
OS_NAME=$(uname -s 2>/dev/null || true)
OS_NAME=${OS_NAME//$'\n'/}
[[ -z "$OS_NAME" ]] && OS_NAME="unknown"
OS_VER=$(sw_vers -productVersion 2>/dev/null || true)
OS_VER=${OS_VER//$'\n'/}
if [[ -z "$OS_VER" ]]; then
  OS_VER=$(uname -r 2>/dev/null || true)
  OS_VER=${OS_VER//$'\n'/}
fi
[[ -z "$OS_VER" ]] && OS_VER="unknown"
OS_FULL="${OS_NAME} ${OS_VER}"

TMP=$(mktemp)
cat > "$TMP" <<EOF
// Package buildinfo holds compile-time build metadata.
//
// Auto-generated by scripts/generate-build-info.sh — do NOT edit by hand.
package buildinfo

var (
	Version   = "${VERSION}"
	Commit    = "${COMMIT}"
	Branch    = "${BRANCH}"
	Date      = "${DATE}"
	GoVersion = "${GOVERSION}"
	OS        = "${OS_FULL}"
)
EOF

if ! cmp -s "$TMP" "$OUT"; then
  mv "$TMP" "$OUT"
  echo "wrote $OUT (version=${VERSION}, commit=${COMMIT})"
else
  rm "$TMP"
fi
