// Package buildinfo holds compile-time build metadata.
//
// Auto-generated by scripts/generate-build-info.sh — do NOT edit by hand.
package buildinfo

var (
	Version   = "0.0.1"
	Commit    = "6c4854b"
	Branch    = "main"
	Date      = "2026-04-27 17:25:47 UTC"
	GoVersion = "1.26.2"
	OS        = "Darwin 26.3.1"
)
